# Generated by Django 4.1 on 2022-10-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_image_likers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="images",
        ),
    ]
